### ISSUE TITLE
Setting a variable to if

### ISSUE THREAD

**Issue by skistaddy** [featurist/pogoscript#65]
When I saw that this language said it had no keywords, and that everything is an object, I immediately tried running the following
```
hello = if

hello (true)
    console.log "hello"
```
Which resulted in the following error
```
TypeError: Cannot read property 'length' of undefined

    at createIfExpression (/usr/local/lib/node_modules/pogo/lib/parser/macros.js:106:13)
    at Object.variable (/usr/local/lib/node_modules/pogo/lib/terms/variable.js:74:28)
    at constructor.expression (/usr/local/lib/node_modules/pogo/lib/parser/complexExpression.js:84:34)
    at gen38_c.expression (/usr/local/lib/node_modules/pogo/lib/parser/operatorExpression.js:124:46)
    at Object.anonymous (/usr/local/lib/node_modules/pogo/lib/parser/jisonParser.js:127:45)
    at Parser.parse (/usr/local/lib/node_modules/pogo/lib/parser/jisonParser.js:335:36)
    at Object.parse (/usr/local/lib/node_modules/pogo/lib/parser/parser.js:29:31)
    at Object.exports.compile (/usr/local/lib/node_modules/pogo/lib/parser/compiler.js:69:29)
    at compileFromFile (/usr/local/lib/node_modules/pogo/lib/parser/commandLine.js:172:24)
    at Object.exports.runFileInModule (/usr/local/lib/node_modules/pogo/lib/parser/commandLine.js:89:14)
```
I'm not sure what this means, but I think it is because of setting `hello` to `if`. If `if` is just an object, I should be theoretically able to run this, right?

**Comment by refractalize** [comment]
ah - `if` is a macro, which is something that is built into the language (even if the syntax is identical to a regular function call), it's not a runtime object that you can assign to something else unfortunately.

At the pogoscript is currently unmaintained but it's here for anybody who's interested

**Comment by skistaddy** [comment]
Ok, good to know. Thank you.
